### ISSUE TITLE
The mac installer does not work

### ISSUE THREAD

**Issue by jackietian** [HyunmoAhn/Tiny-Timer#10]
It seems the mac installer does not work.

**Comment by HyunmoAhn** [comment]
Can you show me about error message? Or just silent?

You downloaded `.dmg` file on README.md, arn't you?

**Comment by jackietian** [comment]
Yep, I downloaded the installer from README.

![screen shot 2018-12-13 at 12 06 55 pm](https://user-images.githubusercontent.com/3350560/49918295-a3e67700-fef6-11e8-996e-1a1af39a6053.png)

**Comment by HyunmoAhn** [comment]
I'm sorry for the late solve of this issue.
I show this alert in my computer. So I fix it.

I release v1.0.1 Tiny-Timer. 
I don't know that why occured this issue exactly.

Difference is that I added Code-Signing to packaging.

To be sure, The above error did not occur when I reinstalled the installation.
